[env:pico]
;platform = raspberrypi@1.20.0
;board = pico
;upload_protocol = picotool
;framework = picosdk
;platform_packages =
;    toolchain-gccarmnoneeabi @ 1.90301.200702

platform = wizio-pico@https://github.com/Wiz-IO/wizio-pico
board = raspberry-pi-pico
framework = baremetal

monitor_speed = 115200
build_flags =
  -DPIO_STDIO_USB
  -DPICO_STDIO_USB_USE_DEFAULT_DESCRIPTORS=0
  -DCFG_TUD_HID=1
  -DCFG_TUD_HID_EP_BUFSIZE=64
